### ISSUE TITLE
TFAR -Script Channle

### ISSUE THREAD

**Issue by john681611** [john681611/co_36_resistance3.Altis#46]
TFAR's module can force a player into a channel when they join.
We need to find out if its possible to script.
It needs to be configurable

https://forums.bistudio.com/topic/159393-task-force-arrowhead-radio/?do=findComment&comment=3116608

**Comment by rhyswilliams999** [comment]
Currently have a script to do that, i've commented out the lines. For our public server, they are not needed as this will not allow us to hear people who are not running it, as setting the channel enable hardcore mode. the other settings are set using the rest of the variables

**Comment by john681611** [comment]
Need to confirm its not broken by save
