### ISSUE TITLE
MHQ vehicles not respawning

### ISSUE THREAD

**Issue by rhyswilliams999** [john681611/co_36_resistance3.Altis#93]
MHQ vehicles not respawning sometimes (i know super "helpful"), resulting in the map marker being at the edge of the map. At times the vehicle does respawn, but does not respawn back at the Main base, but at the edge of the map.

**Comment by john681611** [comment]
hmm more likely a BIS issue but we can have a look

**Comment by john681611** [comment]
Determined its a BIS issue
